import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const {
      studentName,
      fatherName,
      contactNumber,
      whatsappNumber,
      desiredClass,
      medium,
      comments,
    } = body;

    if (!studentName || !fatherName || !contactNumber || !desiredClass) {
      return NextResponse.json(
        { success: false, error: "Required fields are missing." },
        { status: 400 }
      );
    }

    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
      console.error("Missing RESEND_API_KEY environment variable.");
      return NextResponse.json(
        { success: false, error: "Mail service is currently misconfigured." },
        { status: 500 }
      );
    }

    const toEmail = process.env.RESEND_TO_EMAIL || "njpschool2011@gmail.com";

    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 16px; background-color: #fafaf9;">
        <h2 style="color: #c2185b; border-bottom: 2px solid #c2185b; padding-bottom: 10px; margin-top: 0;">New Admission Inquiry Form Submission</h2>
        <p style="font-size: 14px; color: #424242; line-height: 1.5;">You have received a new online admission inquiry submission from the Nav Jeevan Public School web platform.</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px;">
          <tr>
            <td style="padding: 10px 5px; font-weight: bold; border-bottom: 1px solid #eaeaea; color: #616161;" width="40%">Student Name</td>
            <td style="padding: 10px 5px; border-bottom: 1px solid #eaeaea; color: #212121; font-weight: bold;">${studentName}</td>
          </tr>
          <tr>
            <td style="padding: 10px 5px; font-weight: bold; border-bottom: 1px solid #eaeaea; color: #616161;">Father's/Guardian's Name</td>
            <td style="padding: 10px 5px; border-bottom: 1px solid #eaeaea; color: #212121;">${fatherName}</td>
          </tr>
          <tr>
            <td style="padding: 10px 5px; font-weight: bold; border-bottom: 1px solid #eaeaea; color: #616161;">Contact Phone Number</td>
            <td style="padding: 10px 5px; border-bottom: 1px solid #eaeaea; color: #212121;"><a href="tel:${contactNumber}">${contactNumber}</a></td>
          </tr>
          <tr>
            <td style="padding: 10px 5px; font-weight: bold; border-bottom: 1px solid #eaeaea; color: #616161;">WhatsApp Number</td>
            <td style="padding: 10px 5px; border-bottom: 1px solid #eaeaea; color: #212121;">${whatsappNumber ? `<a href="https://wa.me/91${whatsappNumber}">${whatsappNumber}</a>` : "Not provided"}</td>
          </tr>
          <tr>
            <td style="padding: 10px 5px; font-weight: bold; border-bottom: 1px solid #eaeaea; color: #616161;">Desired Admission Class</td>
            <td style="padding: 10px 5px; border-bottom: 1px solid #eaeaea; color: #c2185b; font-weight: bold;">${desiredClass}</td>
          </tr>
          <tr>
            <td style="padding: 10px 5px; font-weight: bold; border-bottom: 1px solid #eaeaea; color: #616161;">Preferred Medium</td>
            <td style="padding: 10px 5px; border-bottom: 1px solid #eaeaea; color: #212121;">${medium || "Not specified"}</td>
          </tr>
        </table>
        
        ${comments ? `
          <div style="margin-top: 25px; padding: 15px; background-color: #ffffff; border-left: 4px solid #c2185b; border-radius: 8px; border-top: 1px solid #eaeaea; border-right: 1px solid #eaeaea; border-bottom: 1px solid #eaeaea;">
            <h4 style="margin: 0 0 8px 0; color: #424242; font-size: 13px;">Additional Inquiries / Comments:</h4>
            <p style="margin: 0; font-size: 13px; color: #616161; line-height: 1.5; white-space: pre-wrap;">${comments}</p>
          </div>
        ` : ""}
        
        <div style="margin-top: 30px; border-top: 1px solid #eaeaea; padding-top: 15px; font-size: 11px; color: #9e9e9e; text-align: center;">
          This message was auto-generated by the Nav Jeevan Public School web platform.
        </div>
      </div>
    `;

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        from: "onboarding@resend.dev",
        to: toEmail,
        subject: `New Admission Inquiry: ${studentName} (${desiredClass})`,
        html: emailHtml,
      }),
    });

    if (!res.ok) {
      const errorText = await res.text();
      console.error("Resend API error response:", errorText);
      let errorMessage = "Failed to send email via Resend API.";
      try {
        const parsed = JSON.parse(errorText);
        if (parsed.message) {
          errorMessage = parsed.message;
        }
      } catch {
        // Ignore parsing errors
      }
      return NextResponse.json(
        { success: false, error: errorMessage },
        { status: 500 }
      );
    }

    const data = await res.json();
    return NextResponse.json({ success: true, data });
  } catch (error: unknown) {
    console.error("Error in admissions route handler:", error);
    const errorMessage =
      error instanceof Error ? error.message : "An unexpected error occurred.";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}
